source 'https://github.com/CocoaPods/Specs.git'

target 'MOAlertController', :exclusive => true do
  pod "MOAlertController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MOAlertController", :path => "../"

  
end
